name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'develop'

jobs:
  build-and-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test

  other-job:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'  # Выполнять только при PR в develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Additional steps for PR to develop
        run: echo "This job runs only on PR to develop branch"